all:
	go build -o ../local/WCMapper WordCountMap.go
	go build -o ../local/WCReduce WordCountReduce.go
	go build -o ../local/WLMapper WebLinkMapper.go
	go build -o ../local/WLReduce WebLinkReduce.go
wordCountMap:
	go build -o ../local/WCMapper WordCountMap.go
wordCountReduce:
	go build -o ../local/WCReduce WordCountReduce.go

